version: "3.3"
services:
  mysql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'movie-dev'
      POSTGRES_USER: 'usr-movie'
      POSTGRES_PASSWORD: 'pwd-movie'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted